### ISSUE TITLE
doubletFinder_v3 bug "only 0's may be mixed with negative subscripts'

### ISSUE THREAD

**Issue by nyuhuyang** [chris-mcginnis-ucsf/DoubletFinder#133] opened 2022-04-15 01:49 UTC
Dont' understand the purpose for commit [8c7f76e](https://github.com/chris-mcginnis-ucsf/DoubletFinder/commit/8c7f76ef0ef41c66982047b13a20daeee9b2f946)

In doubletFinder_v3 function, Below scripts will generate the bug "only 0's may be mixed with negative subscripts'

120   neighbor_types[i,] <- 
121            table( doublet_types1[neighbors - n_real.cells] ) +
122            table( doublet_types2[neighbors - n_real.cells] )

**Comment by ekernf01** [comment] 2022-05-09 19:55
This bug is probably my fault. I learned about this today and I'm going to look into it. The feature is discussed [here](https://github.com/chris-mcginnis-ucsf/DoubletFinder/issues/127). In the meantime, does it work if you omit the `annotations` argument?

**Comment by ekernf01** [comment] 2022-05-10 19:13
I think this should be resolved in the above pull request.

**Comment by lquin003** [comment] 2022-09-16 15:43
I'm still running into this bug when attempting to annotate doublets using the `annotate = as.character(obj$cluster_annotations)` parameter. Do you have an example of the format used to submit and receive annotations?

 I've made sure to set the identity of my seurat object to that specific column. i.e. `obj@active.idents = as.factor(obj$cluster_annotations)`.

**Comment by ekernf01** [comment] 2022-09-16 17:12
The PR above has not been merged, so that could be the problem. Does it work if you omit the `annotations` argument or if you install from the `doublets_by_type` branch?

**Comment by lquin003** [comment] 2022-09-16 17:15
It does work without the annotations argument. I was just hoping to try the annotations argument with my dataset. I'll try to install from the branch. That might work. Thanks!

**Comment by chris-mcginnis-ucsf** [comment] 2023-02-20 02:42
merged!

**Comment by ramin-ali-marandi-ghoddousi** [comment] 2023-03-27 22:45
Hi,

Was this issue every resolved?  I get the same error when I set annotations to as.character(object$seurat_clusters).  Any suggestions?

Thanks!

**Comment by ekernf01** [comment] 2023-03-27 23:09
The merge above was intended to resolve this issue. Can you update to the latest version and see if the issue persists?

**Comment by ramin-ali-marandi-ghoddousi** [comment] 2023-03-27 23:21
I have DoubletFinder_2.0.3 installed via remotes::install_github('chris-mcginnis-ucsf/DoubletFinder').  Is there a more recent version than this?

**Comment by ekernf01** [comment] 2023-03-28 12:16
Probably not. Are you able to share a reprex?

**Comment by ekernf01** [comment] 2023-03-28 18:46
You're welcome. That example is extremely helpful. It works for with the ekernf01 fork, but not with the main repo here, so it seems that the fix did not get fully incorporated. I will put in another pull request now. In the meantime, the best option might be to avoid providing cell type annotations.

**Comment by ramin-ali-marandi-ghoddousi** [comment] 2023-03-28 21:44
Great, thanks.

**Closed** 2023-08-18 22:26 UTC
