### ISSUE TITLE
Doublet finder did not work with SCTransform in my single sample analysis 

### ISSUE THREAD

**Issue by synatkeamsk** [chris-mcginnis-ucsf/DoubletFinder#170] opened 2023-11-11 01:30 UTC
Dear Author, 

I used doublet finder with just one sample using SCTransform paramSweep_v3, it reports error:
Error in NormalizeData.default(object = GetAssayData(object = object, : trying to get slot "params" from an object of a basic class ("NULL") with no slots

However, once used normal seurat pipeline, everything work okay. 

``` 
Normalized.164s<- NormalizeData(Filtered.cells.164s)
Normalized.164s <- FindVariableFeatures(Normalized.164s, selection.method = "vst", nfeatures = 2000)
Normalized.164s <- ScaleData(Normalized.164s)
Normalized.164s <- RunPCA(Normalized.164s, verbose = FALSE)
```

Do you know the reason why? The total cells in that sample is around 7000 cells.

Thanks, 

Synat,

**Comment by MiriamRiquelmeP** [comment] 2023-11-13 17:13
I think the problem is that the Seurat package, in version 5.0, has changed the slot parameter in favour of layers in accessor and set methods. The architecture of the new object is not the same and when function paramSweep_v3 is trying to access some slots (like seu@assays$RNA@counts or orig.commands$NormalizeData.RNA@params$scale.factor on parallel_paramSweep_v3, called by parallel_paramSweep_v3) they do not exist anymore.

Until DoubletFinder doesn't update their code to match the Seurat object, you can downgrade your Seurat version to 4.X.X and it should work.

You can track all the changes here: https://github.com/satijalab/seurat/blob/HEAD/NEWS.md

Best,
Miriam

**Comment by synatkeamsk** [comment] 2023-11-14 02:12
Hi Miriam, 

Thank for your response. I did not downgrade my seurat5 to 4. I kept using seurat 5 and used standard Seurat pipeline to normalize the data for individual sample such as:
``` 
NormalizeData()
FindVariableFeatures()
ScaleData()
RunPCA()
RunUMAP() 
``` 
after that, I used DoubletFinder pipeline to filter out doublet cells and save singlet object for individual sample. Next, I merged all singlet objects for analysis. After merging, I used SCTransform to normalize the data, runPCA, integration using harmony and RunUMAP, FindNeighbor, and FindCluster etc. 

My question, since I normalized data using seurat pipeline for doublet filtering and then switched to SCTransform after merging all singlet object for clustering. Is this the right way? The reason I sticked with SCTransform because I tended to get a good cluster with it. However, weird thing came up. Treg population and CD8 population and CD4 population looked weird in Cluster 7, 8, 11, 13 as they have a bit of those three population. Generally, Treg should stay togeter rather scatting in different cluster far away for each other. Not sure whether these are also doublet. If so, they are big population. 


![clustering](https://github.com/chris-mcginnis-ucsf/DoubletFinder/assets/121846660/4d383442-dc00-42a0-94d1-c4e778372bc0)


![feature plots](https://github.com/chris-mcginnis-ucsf/DoubletFinder/assets/121846660/7f642390-9565-4549-9ab4-feb82ef498a3)



Hope you can give some suggestion as I have no idea of what is happening.

Kind Regards,

synat

**Comment by chris-mcginnis-ucsf** [comment] 2023-11-21 20:30
I just fixed it -- should work with Seurat V5 now. And @MiriamRiquelmeP yes it is fine to remove doublets and then reanalyxe the merged data with SCT

Chris

**Closed by chris-mcginnis-ucsf** 2023-11-21 20:30 UTC

**Comment by synatkeamsk** [comment] 2023-11-29 21:26
Hi Chris, 

I still got error in Seurat V5. 
``` doublet.all<- paramSweep_v3(data.filt, PCs = 1:45, sct = FALSE)

Error in paramSweep_v3(data.filt, PCs = 1:45, sct = FALSE) : 
  no slot of name "counts" for this object of class "Assay5"
``` 
Not sure whether you have fixed it. 

Thanks,

synat
